### PR TITLE
Update commentfaces.css

### PR DESCRIPTION
**Pull request by Riyria4**
Show: Fate Prisma Illya

Comment Faces: ##illyasmile, ##illyapout, ##illyashock, ##illyahappy, ##illyalove

Maybe it'll work this time. This is still an awesome idea and amazing of you to do!

### CODE REVIEW

**Comment by Amndeep7** [comment]
Thanks :)

And I haven't done too much of the actual work yet - you should be thanking the mods who set up this system in the first place.

Also, before I merge your faces in, feel free to increase the size of them if you'd like.  A max dimension of 200px is fine, but if you're fine with a max dimension of 150px, that's fine too.

**Comment by Riyria4** [comment]
How do I do that? I've increased the size of the pictures. Do I submit a new pull request with that or is there some way to edit what I sent?

**Comment by Amndeep7** [comment]
So I think if you go to the "Files Changed" tab, and then there's the two buttons where the first looks like `<>` and the second looks like a document, and then next to those is a button of three dots.  If you click that menu button, there should be an option called "Edit file".  I believe this will let you edit it.  If that doesn't work, feel free to close this request and open up a new one with the changes.  

Don't forget to change both the url and the dimension values!

**Comment by Riyria4** [comment]
Okay. I tried that. And I think something went through. I made sure to change the url and dimensions!

**Pull request merged**
